/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UniversityAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.StudentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AppliedJobRequest;
import Business.WorkQueue.JobResultWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jerin
 */
public class CoopAdvisorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CoopAdvisorJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;
    
    
    
    public CoopAdvisorJPanel(JPanel userProcessContainer,UserAccount account,Organization organization,Enterprise enterprise,EcoSystem business,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        populateJob();
        populateAppliedJob();
        

              
    }
    
      private void populateJob(){
    
        DefaultTableModel model = (DefaultTableModel)cTable.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList())
        {
        Object row[] = new Object[7];
                
                row[0] = request;
                row[1] = request.getJob().getJobId();
                row[2] = request.getJob().getJobType();
                row[3] = request.getJob().getJobLoc();
                row[4] = request.getJob().getJobDesc();
                row[5] = request.getSender().getUsername();
                
                
                //row[6] = request.getReceiver();
                
                model.addRow(row);
        }
    
    }
      
      
public void populateAppliedJob() {
        DefaultTableModel model = (DefaultTableModel) appliedJobTable.getModel();
        model.setRowCount(0);
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof StudentOrganization) {
                for (UserAccount acc : organization.getUserAccountDirectory().getUserAccountList()) {
                    for (WorkRequest wr : acc.getWorkQueue().getWorkRequestList()) {
                        if(wr instanceof AppliedJobRequest)
                        {
                        AppliedJobRequest ajr = (AppliedJobRequest) wr;
                        if (null != ajr.getTestResult() &&
                                ajr.getTestResult().equals(("Reject"))) 
                        {
                            Object[] row = new Object[7];
                            row[0] = ajr;
                            row[1] = ajr.getRequestDate();
                            row[2] = ajr.getStatus();
                            row[3] = ajr.getJob().getJobLoc();
                            row[4] = ajr.getJob().getJobType();
                            row[5] = ajr.getEntName();
                            row[6] = ajr.getTestResult();

                            model.addRow(row);

                        }
                        }
                    }
                }

            }
        }

    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cTable = new javax.swing.JTable();
        btnApply = new javax.swing.JButton();
        btnassignMe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        appliedJobTable = new javax.swing.JTable();
        BtnAssign = new javax.swing.JButton();
        BtnSendMessage = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Msg", "Job Id", "Job Type", "Job Location", "Description", "Sender"
            }
        ));
        jScrollPane1.setViewportView(cTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 122, 954, 127));

        btnApply.setText("Post Jobs");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });
        add(btnApply, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, -1, -1));

        btnassignMe.setText("Assign to me");
        btnassignMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnassignMeActionPerformed(evt);
            }
        });
        add(btnassignMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Co-Op Advisor Panel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 46, -1, -1));

        jLabel2.setText("Company Postings");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel3.setText("Students Applied Jobs");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        appliedJobTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Name", "Sent Date", "Status", "Location", "Job Type", "Company", "Result"
            }
        ));
        jScrollPane2.setViewportView(appliedJobTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 740, 101));

        BtnAssign.setText("Assign to me");
        BtnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAssignActionPerformed(evt);
            }
        });
        add(BtnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        BtnSendMessage.setText("Send Message");
        BtnSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSendMessageActionPerformed(evt);
            }
        });
        add(BtnSendMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        // TODO add your handling code here:

        int selectedjob = cTable.getSelectedRow();
        if(selectedjob >=0)
        {

            WorkRequest jobselected = (WorkRequest)cTable.getValueAt(selectedjob, 0);
            String name = ((JobResultWorkRequest)jobselected).getEnterpriseName();
            String message = "FromCoopToStudent";
            //String date="Today";
            
                Date newDate= new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"); //Or whatever format fits best your needs.
             String dateStr = sdf.format(newDate);

            JobResultWorkRequest request = new JobResultWorkRequest();
            request.setMessage(message);
            request.setJob(jobselected.getJob());
            request.setSender(account);
            request.setRequestDate(dateStr);
            request.setStatus("Sent");
            request.setEnterpriseName(name);
            
            Organization org1 = null;

            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) 
            {
                if (organization instanceof StudentOrganization) 
                {
                    org1 = organization; 
                    break;
                }
            }
   
            if (org1!=null)
            {
                org1.getWorkQueue().getWorkRequestList().add(request);
                account.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "Successful");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please select any row ");
            }

        }

    }//GEN-LAST:event_btnApplyActionPerformed

    private void btnassignMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnassignMeActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = cTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
         WorkRequest request = (WorkRequest)cTable.getValueAt(selectedRow, 0);
        request.setReceiver(account);
        request.setStatus("Pending");
        populateJob();
        
        JOptionPane.showMessageDialog(null, "Assigned Successfully");
    }//GEN-LAST:event_btnassignMeActionPerformed

    private void BtnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAssignActionPerformed
        // TODO add your handling code here:

        int selectedRow = appliedJobTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        WorkRequest request = (WorkRequest) appliedJobTable.getValueAt(selectedRow, 0);
        request.setReceiver(account);
        request.setStatus("Pending");
        populateAppliedJob();

        JOptionPane.showMessageDialog(null, "Assigned Successfully");
    }//GEN-LAST:event_BtnAssignActionPerformed

    private void BtnSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSendMessageActionPerformed
        // TODO add your handling code here:
        int selectedjob = appliedJobTable.getSelectedRow();
        if (selectedjob >= 0) {

            WorkRequest request = (WorkRequest) appliedJobTable.getValueAt(selectedjob, 0);
            SendMessagePanel sendMessagePanel = new SendMessagePanel(userProcessContainer,account,enterprise,business, network,request);
            userProcessContainer.add("sendMessagePanel", sendMessagePanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_BtnSendMessageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAssign;
    private javax.swing.JButton BtnSendMessage;
    private javax.swing.JTable appliedJobTable;
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnassignMe;
    private javax.swing.JTable cTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
