/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UniversityAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.JobResultWorkRequest;
import Business.WorkQueue.StressManagementRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hemantkamath
 */
public class SendMessagePanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;
    private WorkRequest request;
    /**
     * Creates new form SendMessagePanel
     */
    public SendMessagePanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem business, Network network, WorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        this.request=request;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        appText = new javax.swing.JTextField();
        msgTxt = new javax.swing.JTextField();
        MsgSend = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Message");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel2.setText("Appointment No");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        appText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appTextActionPerformed(evt);
            }
        });
        add(appText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 120, -1));
        add(msgTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 120, -1));

        MsgSend.setText("Send Message");
        MsgSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsgSendActionPerformed(evt);
            }
        });
        add(MsgSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void appTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appTextActionPerformed

    private void MsgSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsgSendActionPerformed
        // TODO add your handling code here:
        String message = msgTxt.getText();
        
        StressManagementRequest requ = new StressManagementRequest();
        requ.setStressMessage(message);
        requ.setSender(account);
        requ.setAppointment(appText.getText());
        UserAccount ua = request.getSender();
        requ.setReceiver(ua);
        
        request.getSender().getWorkQueue().getWorkRequestList().add(requ);
        account.getWorkQueue().getWorkRequestList().add(requ);
        
        JOptionPane.showMessageDialog(null, "Appointment Scheduled successfully");
        
       
        
    }//GEN-LAST:event_MsgSendActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MsgSend;
    private javax.swing.JTextField appText;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField msgTxt;
    // End of variables declaration//GEN-END:variables
}
