/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CompanyAdmin.CompanyManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.UniversityEnterprise;
import Business.Network.Network;
import Business.Organization.CompanyDeptOrganization;
import Business.Organization.CoopOrganization;
import Business.Organization.Organization;
import Business.Organization.StudentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.JobDirectory;
import Business.WorkQueue.JobPosting;
import Business.WorkQueue.JobResultWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jerin
 */
public class AddJobPosting extends javax.swing.JPanel {

    /**
     * Creates new form AddJobPosting
     */
    JPanel userProcessContainer;
    
    private UserAccount account;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network network;
    public AddJobPosting(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer =userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.system = system;
        this.network = network;

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFieldJobId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldDesc = new javax.swing.JTextField();
        btnAddJob = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFieldLocation = new javax.swing.JTextField();
        txtFieldYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        boxJobType = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Add Job Posting");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 204, -1));
        add(txtFieldJobId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 204, -1));

        jLabel2.setText("JobID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel3.setText("Job Type:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setText("Desc:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        add(txtFieldDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 204, -1));

        btnAddJob.setText("Add Job");
        btnAddJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJobActionPerformed(evt);
            }
        });
        add(btnAddJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel5.setText("Location:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        txtFieldLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldLocationActionPerformed(evt);
            }
        });
        add(txtFieldLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 173, -1));
        add(txtFieldYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 173, -1));

        jLabel6.setText("Year:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        boxJobType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "WEB", "DATA", "SOFTWARE", "PROJECT MANAGEMENT" }));
        boxJobType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxJobTypeActionPerformed(evt);
            }
        });
        add(boxJobType, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJobActionPerformed
        // TODO add your handling code here:
        
        String id = txtFieldJobId.getText();
        if(!boxJobType.getSelectedItem().toString().equalsIgnoreCase("Select")){
        String jobtype = boxJobType.getSelectedItem().toString();
        
        String desc = txtFieldDesc.getText();
        String loc = txtFieldLocation.getText();
        String year = txtFieldYear.getText();
        
        
        JobDirectory jobdirect = new JobDirectory();
        JobPosting list = jobdirect.AddJob();
        
        list.setJobType(jobtype);
        list.setJobDesc(desc);
        list.setJobLoc(loc);
        list.setJobYear(year);
        list.setJobId(id);
        
        JobResultWorkRequest request = new JobResultWorkRequest();
        request.setMessage("JobPostedToCoop");
        request.setSender(account);
        request.setStatus("SentFromCompany");
        request.setEnterpriseName(enterprise.getName());
        
        
        request.setJob(list);
        
        Organization org = null;
 
        outer:for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) 
        {
            if (enterprise instanceof UniversityEnterprise) 
            {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) 
                {
                    if (organization instanceof CoopOrganization) 
                    {
                        org = organization;
                        org.getWorkQueue().getWorkRequestList().add(request);
                       // break outer ;

                    }
                    
                }
                
            }
        }
        
        account.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Job Added Successfully");
        
         txtFieldJobId.setText("");
         boxJobType.validate();
         txtFieldDesc.setText("");
         txtFieldLocation.setText("");
         txtFieldYear.setText("");
        }
        else{
        JOptionPane.showMessageDialog(null, "PLEASE SELECT A VALUE");
        }
        
        
        
    }//GEN-LAST:event_btnAddJobActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CompanyManagerWorkAreaJPanel dwjp = (CompanyManagerWorkAreaJPanel) component;
        dwjp.populateJobList();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtFieldLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldLocationActionPerformed

    private void boxJobTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxJobTypeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_boxJobTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxJobType;
    private javax.swing.JButton btnAddJob;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFieldDesc;
    private javax.swing.JTextField txtFieldJobId;
    private javax.swing.JTextField txtFieldLocation;
    private javax.swing.JTextField txtFieldYear;
    // End of variables declaration//GEN-END:variables
}
