/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CompanyAdmin.CompanyManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CompanyDeptOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AppliedJobRequest;
import Business.WorkQueue.JobResultWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hemantkamath
 */
public class CompanyManagerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private CompanyDeptOrganization organization;
    EcoSystem business;
    private Network network;

    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public CompanyManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,EcoSystem business, Network network) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.organization = (CompanyDeptOrganization)organization;
        this.business = business;
        this.network = network;
        populateTable();
        populateJobList();
    }
    
    public void populateJobList()
    {
        DefaultTableModel model = (DefaultTableModel)jobPostingTable.getModel();
        model.setRowCount(0);
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList())
        {
           Object[] row = new Object[4];
           row[0] = request;
           row[1] = request.getJob().getJobType();
           row[2] = request.getJob().getJobLoc();
           row[3] = request.getJob().getJobId();
           model.addRow(row);
        }
    }
    
    public void populateTable(){
        
        DefaultTableModel model = (DefaultTableModel)appliedStudentsTable.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList())
        {
            Object[] row = new Object[8];
            row[0] = request;
            row[1] = ((AppliedJobRequest)request).getAppliedJobRequest(); 
            row[2] = request.getRequestDate();
            row[3] = request.getJob().getJobType();
            row[4] = request.getJob().getJobLoc();
            row[5] = request.getReceiver();
            row[6] =((AppliedJobRequest)request).getStream();
            row[7] = enterprise.getName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        processJButton = new javax.swing.JButton();
        btnAddJob = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jobPostingTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        appliedStudentsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        assignJButton = new javax.swing.JButton();
        BtnViewDetails = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1190, 840));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        processJButton.setText("Process Job Application>>");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        btnAddJob.setText("Add Job");
        btnAddJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJobActionPerformed(evt);
            }
        });
        add(btnAddJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        jobPostingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sender", "Job Type", "Job Location", "Job ID"
            }
        ));
        jScrollPane2.setViewportView(jobPostingTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 866, 110));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Company Manages Job ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        appliedStudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student name", "University", "Date", "Job Type", "Job Location", "Assign to", "Stream", "Company"
            }
        ));
        jScrollPane1.setViewportView(appliedStudentsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 866, 114));

        jLabel2.setText("Applied Students");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setText("Jobs Posted");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jButton1.setText("View Job Description");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        BtnViewDetails.setText("View Student Details");
        BtnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewDetailsActionPerformed(evt);
            }
        });
        add(BtnViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
        
        int selectedRow = appliedStudentsTable.getSelectedRow();
        if (selectedRow < 0)
        {
            return;
        }
        
        AppliedJobRequest request = (AppliedJobRequest)appliedStudentsTable.getValueAt(selectedRow, 0);
        request.setStatus("Processing");
        ProcessJobApplicationsJPanel processJobApplicationsJPanel = new ProcessJobApplicationsJPanel(userProcessContainer, request);
        userProcessContainer.add("processJobApplicationsJPanel", processJobApplicationsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_processJButtonActionPerformed

    private void btnAddJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJobActionPerformed
        // TODO add your handling code here:
        AddJobPosting processWorkRequestJPanel = new AddJobPosting(userProcessContainer,userAccount,enterprise,business, network);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddJobActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = appliedStudentsTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        WorkRequest request = (WorkRequest)appliedStudentsTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        populateTable();
    
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void BtnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewDetailsActionPerformed
        // TODO add your handling code here:
        
         int selectedRow = appliedStudentsTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        
        WorkRequest request = (WorkRequest)appliedStudentsTable.getValueAt(selectedRow, 0);
        ViewStudentDetailsPanel viewStudentDetailsPanel = new ViewStudentDetailsPanel(userProcessContainer, request);
        userProcessContainer.add("viewStudentDetailsPanel", viewStudentDetailsPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        

    }//GEN-LAST:event_BtnViewDetailsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnViewDetails;
    private javax.swing.JTable appliedStudentsTable;
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton btnAddJob;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jobPostingTable;
    private javax.swing.JButton processJButton;
    // End of variables declaration//GEN-END:variables
}
