/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CompanyAdmin.CompanyManagerRole;

import Business.Role.StudentRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author hemantkamath
 */
public class ViewStudentDetailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewStudentDetailsPanel
     */
    
    private JPanel userProcessContainer;
    private WorkRequest request;
    public ViewStudentDetailsPanel(JPanel userProcessContainer, WorkRequest request) {
        initComponents();
        this.request=request;
        this.userProcessContainer = userProcessContainer;
        populateDetails();
        
    }
    
    public void populateDetails()
    {
        UserAccount userAccount= request.getSender();
        
        majorTxtField.setText(userAccount.getMajor());
        StudentRole role = (StudentRole) userAccount.getRole();
        firstnameTxtField.setText(userAccount.getFirstName());
        majorTxtField.setText(userAccount.getMajors());
        lastnameTxtField.setText(userAccount.getLastName());
        ssnTxtField.setText(userAccount.getSsn());
        dobTxtField.setText(userAccount.getDob());
        stateTxtField.setText(userAccount.getState());
        PhoneTxtField.setText(userAccount.getPhoneNumber());
        jTextField6.setText(userAccount.getCity());
        emailTxtField.setText(userAccount.getEmail());
        interestJobTxtField.setText(userAccount.getInterestedJob());
        experienceTxtField.setText(userAccount.getWorkexperienxe());
        skill1TxtField.setText(userAccount.getSkill1());
        skill2TxtField.setText(userAccount.getSkill2());
        skill3TxtField.setText(userAccount.getSkill3());
        projectTxtField.setText(userAccount.getProjectSummary());
        awardsTxtField.setText(userAccount.getAwards());
        jTextField16.setText(userAccount.getGithub());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstnameTxtField = new javax.swing.JTextField();
        lastnameTxtField = new javax.swing.JTextField();
        dobTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ssnTxtField = new javax.swing.JTextField();
        stateTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        skill1TxtField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        interestJobTxtField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        experienceTxtField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectTxtField = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PhoneTxtField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        emailTxtField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        majorTxtField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        awardsTxtField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        skill2TxtField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        skill3TxtField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Student Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 166, 25));

        jLabel2.setText("First Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setText("Last Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        firstnameTxtField.setEnabled(false);
        firstnameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTxtFieldActionPerformed(evt);
            }
        });
        add(firstnameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 133, -1));

        lastnameTxtField.setEnabled(false);
        add(lastnameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 134, -1));

        dobTxtField.setEnabled(false);
        add(dobTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 134, -1));

        jLabel4.setText("DOB");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Personal Details");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel6.setText("SSN:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        ssnTxtField.setEnabled(false);
        add(ssnTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 113, -1));

        stateTxtField.setEnabled(false);
        add(stateTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 113, -1));

        jLabel7.setText("State:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel8.setText("City:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jTextField6.setEnabled(false);
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 113, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Job Skills");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel10.setText("Skillset 1:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        skill1TxtField.setEnabled(false);
        add(skill1TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 115, -1));

        jLabel13.setText("Interested Job Type:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        interestJobTxtField.setEnabled(false);
        interestJobTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestJobTxtFieldActionPerformed(evt);
            }
        });
        add(interestJobTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 216, -1));

        jLabel14.setText("Work Experience:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        experienceTxtField.setEnabled(false);
        add(experienceTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 35, -1));

        jLabel15.setText("Years");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        projectTxtField.setColumns(20);
        projectTxtField.setRows(5);
        projectTxtField.setEnabled(false);
        jScrollPane1.setViewportView(projectTxtField);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 394, 34));

        jLabel16.setText("Projects Summary:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jLabel17.setText("Phone:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        PhoneTxtField.setEnabled(false);
        add(PhoneTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 132, -1));

        jLabel18.setText("Email ID:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        emailTxtField.setEnabled(false);
        add(emailTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 134, -1));

        jLabel19.setText("Education/Majors:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        majorTxtField.setEnabled(false);
        add(majorTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 307, -1));

        jLabel20.setText("Awards/Honors:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        awardsTxtField.setEnabled(false);
        add(awardsTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 200, -1));

        jLabel21.setText("LinkedIn");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));

        jTextField16.setEnabled(false);
        add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 200, -1));

        jLabel11.setText("Skillset 2:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        skill2TxtField.setEnabled(false);
        add(skill2TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 115, -1));

        jLabel12.setText("Skillset 3:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        skill3TxtField.setEnabled(false);
        add(skill3TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 115, -1));

        jLabel25.setText("UserName:");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 90, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void interestJobTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestJobTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestJobTxtFieldActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] component1=userProcessContainer.getComponents();
        Component component=component1[component1.length - 1];
        CompanyManagerWorkAreaJPanel companyManagerWorkAreaJPanel=(CompanyManagerWorkAreaJPanel)component;
        companyManagerWorkAreaJPanel.populateTable();
        companyManagerWorkAreaJPanel.populateJobList();
        CardLayout cardLayout=(CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    
    }//GEN-LAST:event_backJButtonActionPerformed

    private void firstnameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PhoneTxtField;
    private javax.swing.JTextField awardsTxtField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField dobTxtField;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JTextField experienceTxtField;
    private javax.swing.JTextField firstnameTxtField;
    private javax.swing.JTextField interestJobTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField lastnameTxtField;
    private javax.swing.JTextField majorTxtField;
    private javax.swing.JTextArea projectTxtField;
    private javax.swing.JTextField skill1TxtField;
    private javax.swing.JTextField skill2TxtField;
    private javax.swing.JTextField skill3TxtField;
    private javax.swing.JTextField ssnTxtField;
    private javax.swing.JTextField stateTxtField;
    // End of variables declaration//GEN-END:variables
}
