/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StudentAdminRole.StudentRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.JobDirectory;
import Business.WorkQueue.JobResultWorkRequest;
import Business.WorkQueue.StressManagementRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hemantkamath
 */
public class NotificationJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private Network network;
    private UserAccount userAccount;
    private JobDirectory jobList;
    private EcoSystem business;
    /**
     * Creates new form NotificationJPanel
     */
    public NotificationJPanel(JPanel userProcessContainer,UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem business, Network network ) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.organization=organization;
        this.enterprise=enterprise;
        this.business=business;
        this.network=network;
        popTable();
        
    }
    
    public void popTable(){
         DefaultTableModel model = (DefaultTableModel) stressTable.getModel();
        model.setRowCount(0);
        
         for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
             if(request instanceof StressManagementRequest){
            Object row[] = new Object[3];
            row[0] = request;
            row[1] = ((StressManagementRequest) request).getAppointment();
            row[2] = request.getSender();
            model.addRow(row);
             }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        stressTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Message", "Appointment No", "Coop Advisor"
            }
        ));
        jScrollPane1.setViewportView(stressTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 504, 91));

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable stressTable;
    // End of variables declaration//GEN-END:variables
}
