/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StudentAdminRole.StudentRole;

import Business.EcoSystem;
import Business.Enterprise.CompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CompanyDeptOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AppliedJobRequest;
import Business.WorkQueue.JobResultWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jerin
 */
//only if the valuse are not null
public class SkillSetAnalysis extends javax.swing.JPanel {

    /**
     * Creates new form SkillSetAnalysis
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    EcoSystem business;
    WorkRequest workrequest;
    String companyname;
    String jobType;
    public SkillSetAnalysis(JPanel userProcessContainer,EcoSystem business,UserAccount userAccount, WorkRequest workrequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.workrequest = workrequest;
        populateConnectionTable();
    }
    
    
    public void populateConnectionTable(){
    
        companyname = ((JobResultWorkRequest)workrequest).getEnterpriseName().toString();
        jobType = workrequest.getJob().getJobType();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        
        
            for(Network net : business.getNetworkList()){
            for(Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()){
                if(ent instanceof CompanyEnterprise){
                for(Organization org : ent.getOrganizationDirectory().getOrganizationList()){
                    if(org instanceof CompanyDeptOrganization){
                           for(WorkRequest req : org.getWorkQueue().getWorkRequestList()){
                               if(req instanceof AppliedJobRequest){
                                   

                                       if(((AppliedJobRequest) req).getEntName().equalsIgnoreCase(companyname)){
                                           
                                           if(req.getJob().getJobType().equalsIgnoreCase(jobType))
                                           {
                                                 if(((AppliedJobRequest) req).getTestResult().equalsIgnoreCase("hired")){
                                                   
                                                     Object row[] = new Object[4];
                                                     row[0] = req.getSender().getFirstName();
                                                     row[1] = req.getSender().getLastName();
                                                     row[2] = req.getSender().getGithub();
                                                     row[3] = req.getSender().getEmail();
                                                     model.addRow(row);
                                                   System.out.println(((AppliedJobRequest) req).getSender()+" "+((AppliedJobRequest) req).getSender().getSkill1());
                                                                              
                                                                        }
                                                                        
                                               
                                           }
                                           
                                       
                                       }
                                   
                                   
                               }
         
                               }
                           }
                    }
                }
            }
            }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Linkedin", "Email ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 651, 183));

        jLabel1.setText("GET A GLANCE TO THE ENVIRONMENT OF THE COMPANY BY CONNECTING TO YOUR ALUMINI ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jButton3.setText("<< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
