/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StudentAdminRole.StudentRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.StudentOrganization;
import Business.Role.StudentRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.JobDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sangh
 */
public class StudentFrontPage extends javax.swing.JPanel {

    /**
     * Creates new form StudentFrontPage
     */
     private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private Network network;
    private UserAccount userAccount;
    private JobDirectory jobList;
    private EcoSystem business;
    
    public StudentFrontPage(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = (StudentOrganization) organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        this.network = network;
        StudentRole s= (StudentRole) account.getRole();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jobSearchBtn = new javax.swing.JButton();
        studentProfileBtn = new javax.swing.JButton();
        studentNotificationBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1190, 840));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jobSearchBtn.setText("SEE JOBS");
        jobSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobSearchBtnActionPerformed(evt);
            }
        });
        add(jobSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 260, 176, -1));

        studentProfileBtn.setText("MANAGE PROFILE");
        studentProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentProfileBtnActionPerformed(evt);
            }
        });
        add(studentProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 318, 176, -1));

        studentNotificationBtn.setText("NOTIFICATIONS");
        studentNotificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNotificationBtnActionPerformed(evt);
            }
        });
        add(studentNotificationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 202, 176, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO HOMEPAGE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 137, 368, 26));
    }// </editor-fold>//GEN-END:initComponents

    private void studentProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentProfileBtnActionPerformed
        // TODO add your handling code here:
         StudentDetailsJPanel panel = new StudentDetailsJPanel(userProcessContainer,business ,userAccount );
        userProcessContainer.add("personWorkArea", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_studentProfileBtnActionPerformed

    private void jobSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobSearchBtnActionPerformed
        // TODO add your handling code here:
         StudentWorkAreaJPanel panel = new StudentWorkAreaJPanel(userProcessContainer,  userAccount,  organization,  enterprise,business,network );
        userProcessContainer.add("personWorkArea", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jobSearchBtnActionPerformed

    private void studentNotificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNotificationBtnActionPerformed
        // TODO add your handling code here:
        NotificationJPanel panel = new NotificationJPanel(userProcessContainer,  userAccount,  organization,  enterprise,business,network );
        userProcessContainer.add("panel23", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_studentNotificationBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jobSearchBtn;
    private javax.swing.JButton studentNotificationBtn;
    private javax.swing.JButton studentProfileBtn;
    // End of variables declaration//GEN-END:variables
}
