/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StudentAdminRole.StudentRole;

import Business.EcoSystem;
import Business.Role.StudentRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import pojo.business;
import pojo.student;
import pojo.studentDirectory;

/**
 *
 * @author Jerin
 */
public class StudentDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentDetailsJPanel
     */
    private EcoSystem Bussn;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    public StudentDetailsJPanel() {
       
    }

    StudentDetailsJPanel(JPanel userProcessContainer, EcoSystem business,UserAccount userAccount ) {
         this.userProcessContainer = userProcessContainer;
         this.Bussn = business;
         this.userAccount = userAccount;
          initComponents();
          jTextField1.setText(userAccount.getUsername());
          pop();
          
        //To change body of generated methods, choose Tools | Templates.
        }
    public void populate(){
        StudentRole role = (StudentRole)userAccount.getRole();
        userAccount.setMajor(majorTxtField.getText());
        userAccount.setFirstName(firstnameTxtField.getText());
        userAccount.setMajors(majorTxtField.getText());
        userAccount.setLastName(lastnameTxtField.getText());
        userAccount.setSsn(ssnTxtField.getText());
        userAccount.setDob(dobTxtField.getText());
        userAccount.setState(stateTxtField.getText());
        userAccount.setPhoneNumber(PhoneTxtField.getText());
        userAccount.setCity(jTextField6.getText());
        userAccount.setEmail(emailTxtField.getText());
        userAccount.setInterestedJob(interestJobTxtField.getText());
        userAccount.setWorkexperienxe(experienceTxtField.getText());
        userAccount.setSkill1(skill1TxtField.getText());
        userAccount.setSkill2(skill2TxtField.getText());
        userAccount.setSkill3(skill3TxtField.getText());
        userAccount.setProjectSummary(projectTxtField.getText());
        userAccount.setAwards(awardsTxtField.getText());
        userAccount.setGithub(jTextField16.getText());
        
       
    }
    
    public void pop(){
    
        majorTxtField.setText(userAccount.getMajor());
        StudentRole role = (StudentRole) userAccount.getRole();
        firstnameTxtField.setText(userAccount.getFirstName());
        majorTxtField.setText(userAccount.getMajors());
        lastnameTxtField.setText(userAccount.getLastName());
        ssnTxtField.setText(userAccount.getSsn());
        dobTxtField.setText(userAccount.getDob());
        stateTxtField.setText(userAccount.getState());
        PhoneTxtField.setText(userAccount.getPhoneNumber());
        jTextField6.setText(userAccount.getCity());
        emailTxtField.setText(userAccount.getEmail());
        interestJobTxtField.setText(userAccount.getInterestedJob());
        experienceTxtField.setText(userAccount.getWorkexperienxe());
        skill1TxtField.setText(userAccount.getSkill1());
        skill2TxtField.setText(userAccount.getSkill2());
        skill3TxtField.setText(userAccount.getSkill3());
        projectTxtField.setText(userAccount.getProjectSummary());
        awardsTxtField.setText(userAccount.getAwards());
        jTextField16.setText(userAccount.getGithub());
        
 
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstnameTxtField = new javax.swing.JTextField();
        lastnameTxtField = new javax.swing.JTextField();
        dobTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ssnTxtField = new javax.swing.JTextField();
        stateTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        skill1TxtField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        interestJobTxtField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        experienceTxtField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectTxtField = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PhoneTxtField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        emailTxtField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        majorTxtField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        awardsTxtField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        skill2TxtField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        skill3TxtField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1205, 842));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Student Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 166, 25));

        jLabel2.setText("First Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setText("Last Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        add(firstnameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 133, -1));
        add(lastnameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 134, -1));
        add(dobTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 134, -1));

        jLabel4.setText("DOB");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Personal Details");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel6.setText("SSN:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));
        add(ssnTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 113, -1));
        add(stateTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 113, -1));

        jLabel7.setText("State:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel8.setText("City:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 113, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Job Skills");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel10.setText("Skillset 1:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));
        add(skill1TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 115, -1));

        jLabel13.setText("Interested Job Type:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        interestJobTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestJobTxtFieldActionPerformed(evt);
            }
        });
        add(interestJobTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 216, -1));

        jLabel14.setText("Work Experience:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));
        add(experienceTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 35, -1));

        jLabel15.setText("Years");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        projectTxtField.setColumns(20);
        projectTxtField.setRows(5);
        jScrollPane1.setViewportView(projectTxtField);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 394, 34));

        jLabel16.setText("Projects Summary:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jLabel17.setText("Phone:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        add(PhoneTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 132, -1));

        jLabel18.setText("Email ID:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        add(emailTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 134, -1));

        jLabel19.setText("Education/Majors:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));
        add(majorTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 307, -1));

        jLabel20.setText("Awards/Honors:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));
        add(awardsTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 200, -1));

        jLabel21.setText("LinkedIn");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));
        add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 200, -1));

        jLabel22.setText("Options: (Java, Python, Databases, Web)");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        jLabel23.setText("Options: (Java, Python, Databases, Web)");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, -1, -1));

        jLabel11.setText("Skillset 2:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));
        add(skill2TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 115, -1));

        jLabel24.setText("Options: (Java, Python, Databases, Web)");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));

        jLabel12.setText("Skillset 3:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));
        add(skill3TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 115, -1));

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 141, -1));

        jLabel25.setText("UserName:");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 110, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
         Pattern pattern = Pattern.compile("^[A-Za-z0-9 ]{1,15}$");
        String fn = firstnameTxtField.getText();
        String ln=lastnameTxtField.getText();
        String mt=majorTxtField.getText();
        String st=stateTxtField.getText();
        String ct= jTextField6.getText();
        
        String dt=dobTxtField.getText();
        String ssn=ssnTxtField.getText();
        
        Matcher m = pattern.matcher(fn);
        Matcher n= pattern.matcher(ln);
        Matcher o=pattern.matcher(mt);
        Matcher p=pattern.matcher(st);
        Matcher q=pattern.matcher(ct);
        
        Pattern pattern1=Pattern.compile("^[0-9 ]{1,10}$");
        Matcher a= pattern1.matcher(ssn);
        
        if(!m.matches() || !n.matches() || !o.matches() || !p.matches() || !q.matches() || !a.matches()  )
        {
            JOptionPane.showMessageDialog(null,"Enter valid credentials");
        }
         
       else {
        
        
        populate();
        
        JOptionPane.showMessageDialog(null,"Data Added Successfully");
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void interestJobTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestJobTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestJobTxtFieldActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PhoneTxtField;
    private javax.swing.JTextField awardsTxtField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField dobTxtField;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JTextField experienceTxtField;
    private javax.swing.JTextField firstnameTxtField;
    private javax.swing.JTextField interestJobTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField lastnameTxtField;
    private javax.swing.JTextField majorTxtField;
    private javax.swing.JTextArea projectTxtField;
    private javax.swing.JTextField skill1TxtField;
    private javax.swing.JTextField skill2TxtField;
    private javax.swing.JTextField skill3TxtField;
    private javax.swing.JTextField ssnTxtField;
    private javax.swing.JTextField stateTxtField;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
