/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.CompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CompanyDeptOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.AppliedJobRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author sangh
 */
public class networkLevelAnalysis extends javax.swing.JPanel {

    /**
     * Creates new form networkLevelAnalysis
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private ArrayList<String> salesName3;
    public networkLevelAnalysis(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.salesName3= new ArrayList<String>();
        pop();
    }

    public void pop(){
        jComboNetwork.removeAll();
        for(Network network : system.getNetworkList()){
            jComboNetwork.addItem(network.getName());
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        boxCombo = new javax.swing.JComboBox<>();
        jComboNetwork = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        skillsetTxt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("VIEW ANALYSIS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 195, 147, -1));

        boxCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "WEB", "DATA", "SOFTWARE", "PROJECT MANAGEMENT" }));
        add(boxCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 134, 153, -1));

        jComboNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboNetworkActionPerformed(evt);
            }
        });
        add(jComboNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 153, -1));

        jLabel1.setText("Network");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jLabel2.setText("SkillSets");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 138, -1, -1));

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel3.setText("Network Level Analysis");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 25, -1, -1));
        add(skillsetTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 61, -1));

        jLabel4.setText("DETAILED ANALYSIS BY SKILLSKET OF NUMBER STUDENTS APPLIED FOR THAT SKILL AND HIRED");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String network = jComboNetwork.getSelectedItem().toString();
        String jobType = boxCombo.getSelectedItem().toString();
        
        for(Network net : system.getNetworkList()){
                if(net.getName().equalsIgnoreCase(network)){
                            for(Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()){
                                if(ent instanceof CompanyEnterprise ){
                                    for( Organization org : ent.getOrganizationDirectory().getOrganizationList()){
                                            if(org instanceof CompanyDeptOrganization){
                                                for(WorkRequest req : org.getWorkQueue().getWorkRequestList()){
                                                    if(req instanceof AppliedJobRequest){
                                                                    
                                                                if(req.getJob().getJobType().equalsIgnoreCase(jobType)){
                                                                    
                                                                        if(((AppliedJobRequest) req).getTestResult().equalsIgnoreCase("hired")){
                                                                                salesName3.add(((AppliedJobRequest) req).getTestResult());
                                                                        }
                                                                        else if(((AppliedJobRequest) req).getTestResult().equalsIgnoreCase("reject")){
                                                                                salesName3.add(((AppliedJobRequest) req).getTestResult());
                                                                        }
                                                                        
                                                                }
                                                    }
                                                }
                                            }
                                    
                                    }
                                }
                            }
                        
                }
        }
         Map<String, Long> map = salesName3.stream()
        .collect(Collectors.groupingBy(w -> w, Collectors.counting()));

     List<Map.Entry<String, Long>> result = map.entrySet().stream()
        .sorted(Map.Entry.comparingByValue(Comparator.reverseOrder()))
        
        .collect(Collectors.toList());
        for(int i=0; i<result.size() ; i++){
            System.out.println(result.get(i).getValue() + "  " + result.get(i).getKey());
            
        }

       
        
         DefaultPieDataset pieDataset = new DefaultPieDataset();
        for(int i=0; i<result.size() ; i++){
            pieDataset.setValue(result.get(i).getKey(), new Long(result.get(i).getValue()));
        }
       
        JFreeChart chart = ChartFactory.createPieChart3D("Parameter Pie chart", pieDataset, true, true, true);
        //jfreeChart = ChartFactory.createPieChart("Parameter Pie chart", pieDataset, true, true, true);
        PiePlot3D p =(PiePlot3D)chart.getPlot();
        ChartFrame frame = new ChartFrame("Pie chart",chart);
        frame.setVisible(true);
        frame.setSize(450, 500);
        
        skillsetTxt.setText(jobType);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboNetworkActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jComboNetworkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel skillsetTxt;
    // End of variables declaration//GEN-END:variables
}
